# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os



# Import API key
from api_keys import g_key

#gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
# Output File (CSV)
output_data_file = "Cities_Output.csv"


v_df = pd.read_csv(output_data_file)
v_df

,Unnamed: 0,City Id,City,Max Temp,Humidity,Wind Speed,Cloudiness,Country,Date,Lat,Lng
0,0,1,hettstedt,3.33,68,3.60,72,DE,1583393752,51.65,11.50
1,1,3,norman wells,-25.00,75,3.60,90,CA,1583393752,65.28,-126.83
2,2,4,grand gaube,29.44,94,5.10,40,MU,1583393753,-20.01,57.66
3,3,5,samarai,26.91,84,1.56,95,PG,1583393753,-10.62,150.67
4,4,6,phulabani,31.09,31,1.25,76,IN,1583393753,20.47,84.23
...,...,...,...,...,...,...,...,...,...,...,...
555,555,605,marsabit,30.41,43,6.18,86,KE,1583393950,2.33,37.99
556,556,606,kenora,-3.00,92,5.70,90,CA,1583393950,49.82,-94.43
557,557,607,borovoy,-1.00,86,7.00,90,RU,1583393951,55.43,86.08
558,558,608,medvedka,-5.36,80,4.01,79,RU,1583393951,61.16,46.39
559,559,609,upata,20.10,93,2.61,26,VE,1583393951,8.01,-62.40

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
#Use the Lat and Lng as locations and Humidity as the weight.
v = v_df[['Lat', 'Lng']]
weights = v_df['Humidity']

In [4]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(v, weights=weights, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
nw_df = v_df.loc[v_df["Max Temp"] > 25]
nw_df.head()

,Unnamed: 0,City Id,City,Max Temp,Humidity,Wind Speed,Cloudiness,Country,Date,Lat,Lng
2,2,4,grand gaube,29.44,94,5.10,40,MU,1583393753,-20.01,57.66
3,3,5,samarai,26.91,84,1.56,95,PG,1583393753,-10.62,150.67
4,4,6,phulabani,31.09,31,1.25,76,IN,1583393753,20.47,84.23
7,7,9,butaritari,28.51,80,8.48,100,KI,1583393754,3.07,172.79
10,10,12,mahebourg,29.44,94,5.10,40,MU,1583393755,-20.41,57.70

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [10]:
# geocoordinates
target_coordinates = nw_df[["Lat", "Lng"]]
target_radius = 5000
target_type = "hotel"

# set up a parameters dictionary
params = {
    "location": target_coordinates,
    "radius": target_radius,
    "type": target_type,
    "key": g_key
}

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=Lat&location=Lng&radius=5000&type=hotel&key=AIzaSyB9Gix2SE21au-sYQlzghncbzvObM-wHio

In [ ]:
cities_df = nw_df['City']

hotel = []

# use iterrows to iterate through pandas dataframe
for city in cities:
    hotels = requests.get(base_url + city).json
    hotel.append(hotels)
    print(f"for {cities} stay in {hotels}")

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display Map